Make snippy report optional
BCCDC-PHL/snippy-variants pull request #14
Opened 2024-10-25 20:40 UTC by jpalmer37

2024-10-28 22:04 UTC, dfornika requested changes
Could we consider inverting the logic on this parameter? This would change the default behavior which may break some analyses that might use those outputs. If we switch it to something like `--skip-report` then the default behavior will be preserved and we'll still be able to exclude those outputs when we want to

2024-10-31 12:30 UTC, JamesZlosnik commented
Just to note, I have tested this on a run containing 20 samples of GAS, resulted in a nearly 15G drop in folder size:

![image](https://github.com/user-attachments/assets/487476da-bbc5-4273-b79c-3fcf3fab5308)

2024-11-04 22:10 UTC, dfornika approved these changes
Looks good!

2024-11-04 22:26 UTC, dfornika approved these changes

2024-11-04 22:27 UTC, merged